#!/bin/sh

# N.B. a little inconsistent; master writes, others exec

set -e

NODE_TYPE=$1
PORT=$2
LOCATOR_PORT=$3
MODEL=$4
N_HOSTS=$5
N_CHUNKS_PER_HOST=$6

set -u

if [ $NODE_TYPE != locator ]; then
	ADDL_ARGS="locator_host='localhost', locator_port=${LOCATOR_PORT}L"
fi

if [ $NODE_TYPE != master ]; then
	for chunknumber in $(seq N_CHUNKS_PER_HOST); do
		pipename="/tmp/chunk-$port-$chunknumber"
		mkfifo "$pipename"
		# write gen_fake_data m x n/(n_chunks*n_hosts)  for host at $port to pipe
		R -se <<-EOF &
		# fake_data($m,$n) |>
		# write_to_pipe("$pipename")
		EOF
	done
	exec R -s <<- EOF
	library(largescaler)
	chunknet::${NODE_TYPE}_node("localhost", ${PORT}L,
	                            verbose=TRUE, $ADDL_ARGS)
	EOF
else
	cat <<-EOF
		library(largescaler)
		chunknet::LOCATOR(${ADDL_ARGS})
		# get chunks to read their data from corresponding pipes (X)
		# create new variable a = X%*%b
		# run $model
	EOF
fi
