"""
This type stub file was generated by pyright.
"""

from typing import Any

class Node:
    def __init__(
        self,
        type_annotation: str | None,
        name: str | None,
        args: list[Any] | None,
        properties: dict[str, Any] | None,
        children: list[Node] | None,
    ) -> None: ...

class Document: ...
