"""
This type stub file was generated by pyright.
"""

from typing import Any

class Node:
    def __init__(
        self,
        name: str | None = None,
        args: list[Any] | None = None,
        properties: dict[str, Any] | None = None,
        children: list[Node] | None = None,
    ) -> None: ...

class EmitterOptions:
    def __init__(
        self,
        *args: Any,
        **kwargs: Any
            ) -> None: ...

class Document:
    def __init__(
        self,
        *args: Node
    ) -> None: ...

    def dump(self, opts: EmitterOptions) -> str: ...
