"""
This type stub file was generated by pyright.
"""

"""Enables use of Python Fire as a "main" function (i.e. "python -m fire").

This allows using Fire with third-party libraries without modifying their code.
"""
cli_string = ...
def import_from_file_path(path): # -> tuple[ModuleType, Any]:
  """Performs a module import given the filename.

  Args:
    path (str): the path to the file to be imported.

  Raises:
    IOError: if the given file does not exist or importlib fails to load it.

  Returns:
    Tuple[ModuleType, str]: returns the imported module and the module name,
      usually extracted from the path itself.
  """
  ...

def import_from_module_name(module_name): # -> tuple[ModuleType, Any]:
  """Imports a module and returns it and its name."""
  ...

def import_module(module_or_filename): # -> tuple[ModuleType, Any]:
  """Imports a given module or filename.

  If the module_or_filename exists in the file system and ends with .py, we
  attempt to import it. If that import fails, try to import it as a module.

  Args:
    module_or_filename (str): string name of path or module.

  Raises:
    ValueError: if the given file is invalid.
    IOError: if the file or module can not be found or imported.

  Returns:
    Tuple[ModuleType, str]: returns the imported module and the module name,
      usually extracted from the path itself.
  """
  ...

def main(args): # -> None:
  """Entrypoint for fire when invoked as a module with python -m fire."""
  ...

if __name__ == '__main__':
  ...
