"""
This type stub file was generated by pyright.
"""

from fire import docstrings, testutils

"""Tests for fire docstrings module."""
DocstringInfo = docstrings.DocstringInfo
ArgInfo = docstrings.ArgInfo
KwargInfo = docstrings.KwargInfo
class DocstringsTest(testutils.BaseTestCase):
  def test_one_line_simple(self): # -> None:
    ...
  
  def test_one_line_simple_whitespace(self): # -> None:
    ...
  
  def test_one_line_too_long(self): # -> None:
    ...
  
  def test_one_line_runs_over(self): # -> None:
    ...
  
  def test_one_line_runs_over_whitespace(self): # -> None:
    ...
  
  def test_google_format_args_only(self): # -> None:
    ...
  
  def test_google_format_arg_named_args(self): # -> None:
    ...
  
  def test_google_format_typed_args_and_returns(self): # -> None:
    ...
  
  def test_google_format_multiline_arg_description(self): # -> None:
    ...
  
  def test_rst_format_typed_args_and_returns(self): # -> None:
    ...
  
  def test_numpy_format_typed_args_and_returns(self): # -> None:
    ...
  
  def test_numpy_format_multiline_arg_description(self): # -> None:
    ...
  
  def test_multisection_docstring(self): # -> None:
    ...
  
  def test_google_section_with_blank_first_line(self): # -> None:
    ...
  
  def test_ill_formed_docstring(self): # -> None:
    ...
  
  def test_strip_blank_lines(self): # -> None:
    ...
  
  def test_numpy_colon_in_description(self): # -> None:
    ...
  
  def test_rst_format_typed_args_and_kwargs(self): # -> None:
    ...
  


if __name__ == '__main__':
  ...
