"""
This type stub file was generated by pyright.
"""

from fire import testutils

"""Tests importing the fire module."""
class FireImportTest(testutils.BaseTestCase):
  """Tests importing Fire."""
  def testFire(self): # -> None:
    ...
  
  def testFireMethods(self): # -> None:
    ...
  
  def testNoPrivateMethods(self): # -> None:
    ...
  


if __name__ == '__main__':
  ...
