"""
This type stub file was generated by pyright.
"""

from fire import testutils

"""Tests for formatting.py."""
LINE_LENGTH = ...
class FormattingTest(testutils.BaseTestCase):
  def test_bold(self): # -> None:
    ...
  
  def test_underline(self): # -> None:
    ...
  
  def test_indent(self): # -> None:
    ...
  
  def test_indent_multiple_lines(self): # -> None:
    ...
  
  def test_wrap_one_item(self): # -> None:
    ...
  
  def test_wrap_multiple_items(self): # -> None:
    ...
  
  def test_ellipsis_truncate(self): # -> None:
    ...
  
  def test_ellipsis_truncate_not_enough_space(self): # -> None:
    ...
  
  def test_ellipsis_middle_truncate(self): # -> None:
    ...
  
  def test_ellipsis_middle_truncate_not_enough_space(self): # -> None:
    ...
  


if __name__ == '__main__':
  ...
