"""
This type stub file was generated by pyright.
"""

"""Formatting utilities for use in creating help text."""
ELLIPSIS = ...
def Indent(text, spaces=...): # -> LiteralString:
  ...

def Bold(text): # -> str:
  ...

def Underline(text): # -> str:
  ...

def BoldUnderline(text): # -> str:
  ...

def WrappedJoin(items, separator=..., width=...): # -> list[Any]:
  """Joins the items by the separator, wrapping lines at the given width."""
  ...

def Error(text): # -> str:
  ...

def EllipsisTruncate(text, available_space, line_length):
  """Truncate text from the end with ellipsis."""
  ...

def EllipsisMiddleTruncate(text, available_space, line_length):
  """Truncates text from the middle with ellipsis."""
  ...

def DoubleQuote(text):
  ...

