"""
This type stub file was generated by pyright.
"""

from fire import testutils

"""Tests for the inspectutils module."""
class InspectUtilsTest(testutils.BaseTestCase):
  def testGetFullArgSpec(self): # -> None:
    ...
  
  def testGetFullArgSpecPy3(self): # -> None:
    ...
  
  def testGetFullArgSpecFromBuiltin(self): # -> None:
    ...
  
  def testGetFullArgSpecFromSlotWrapper(self): # -> None:
    ...
  
  def testGetFullArgSpecFromNamedTuple(self): # -> None:
    ...
  
  def testGetFullArgSpecFromNamedTupleSubclass(self): # -> None:
    ...
  
  def testGetFullArgSpecFromClassNoInit(self): # -> None:
    ...
  
  def testGetFullArgSpecFromMethod(self): # -> None:
    ...
  
  def testInfoOne(self): # -> None:
    ...
  
  def testInfoClass(self): # -> None:
    ...
  
  def testInfoClassNoInit(self): # -> None:
    ...
  
  def testInfoNoDocstring(self): # -> None:
    ...
  


if __name__ == '__main__':
  ...
