"""
This type stub file was generated by pyright.
"""

from unittest import mock
from fire import testutils

"""Tests for the interact module."""
INTERACT_METHOD = ...
class InteractTest(testutils.BaseTestCase):
  @mock.patch(INTERACT_METHOD)
  def testInteract(self, mock_interact_method): # -> None:
    ...
  
  @mock.patch(INTERACT_METHOD)
  def testInteractVariables(self, mock_interact_method): # -> None:
    ...
  


if __name__ == '__main__':
  ...
