"""
This type stub file was generated by pyright.
"""

from fire import testutils

"""Test using Fire via `python -m fire`."""
class MainModuleTest(testutils.BaseTestCase):
  """Tests to verify the behavior of __main__ (python -m fire)."""
  def testNameSetting(self): # -> None:
    ...
  
  def testArgPassing(self): # -> None:
    ...
  


class MainModuleFileTest(testutils.BaseTestCase):
  """Tests to verify correct import behavior for file executables."""
  def setUp(self): # -> None:
    ...
  
  def testFileNameFire(self): # -> None:
    ...
  
  def testFileNameFailure(self): # -> None:
    ...
  
  def testFileNameModuleDuplication(self): # -> None:
    ...
  
  def testFileNameModuleFileFailure(self): # -> None:
    ...
  


if __name__ == '__main__':
  ...
