"""
This type stub file was generated by pyright.
"""

from fire import testutils

"""Tests for the parser module."""
class ParserTest(testutils.BaseTestCase):
  def testCreateParser(self): # -> None:
    ...
  
  def testSeparateFlagArgs(self): # -> None:
    ...
  
  def testDefaultParseValueStrings(self): # -> None:
    ...
  
  def testDefaultParseValueQuotedStrings(self): # -> None:
    ...
  
  def testDefaultParseValueSpecialStrings(self): # -> None:
    ...
  
  def testDefaultParseValueNumbers(self): # -> None:
    ...
  
  def testDefaultParseValueStringNumbers(self): # -> None:
    ...
  
  def testDefaultParseValueQuotedStringNumbers(self): # -> None:
    ...
  
  def testDefaultParseValueOtherNumbers(self): # -> None:
    ...
  
  def testDefaultParseValueLists(self): # -> None:
    ...
  
  def testDefaultParseValueBareWordsLists(self): # -> None:
    ...
  
  def testDefaultParseValueDict(self): # -> None:
    ...
  
  def testDefaultParseValueNone(self): # -> None:
    ...
  
  def testDefaultParseValueBool(self): # -> None:
    ...
  
  def testDefaultParseValueBareWordsTuple(self): # -> None:
    ...
  
  def testDefaultParseValueNestedContainers(self): # -> None:
    ...
  
  def testDefaultParseValueComments(self): # -> None:
    ...
  
  def testDefaultParseValueBadLiteral(self): # -> None:
    ...
  
  def testDefaultParseValueSyntaxError(self): # -> None:
    ...
  
  def testDefaultParseValueIgnoreBinOp(self): # -> None:
    ...
  


if __name__ == '__main__':
  ...
