"""
This type stub file was generated by pyright.
"""

import functools
from typing import Tuple

"""This module has components that use Python 3 specific syntax."""
def identity(arg1, arg2: int, arg3=..., arg4: int = ..., *arg5, arg6, arg7: int, arg8=..., arg9: int = ..., **arg10): # -> tuple[Any, int, int, int, tuple[Any, ...], Any, int, int, int, dict[str, Any]]:
  ...

class HelpTextComponent:
  def identity(self, *, alpha, beta=...): # -> tuple[Any, str]:
    ...
  


class KeywordOnly:
  def double(self, *, count):
    ...
  
  def triple(self, *, count):
    ...
  
  def with_default(self, *, x=...): # -> None:
    ...
  


class LruCacheDecoratedMethod:
  @functools.lru_cache()
  def lru_cache_in_class(self, arg1):
    ...
  


@functools.lru_cache()
def lru_cache_decorated(arg1):
  ...

class WithAsyncio:
  async def double(self, count=...): # -> int:
    ...
  


class WithTypes:
  """Class with functions that have default arguments and types."""
  def double(self, count: float) -> float:
    """Returns the input multiplied by 2.

    Args:
      count: Input number that you want to double.

    Returns:
      A number that is the double of count.
    """
    ...
  
  def long_type(self, long_obj: Tuple[Tuple[Tuple[Tuple[Tuple[Tuple[Tuple[Tuple[Tuple[Tuple[Tuple[Tuple[int]]]]]]]]]]]]): # -> Tuple[Tuple[Tuple[Tuple[Tuple[Tuple[Tuple[Tuple[Tuple[Tuple[Tuple[Tuple[int]]]]]]]]]]]]:
    ...
  


class WithDefaultsAndTypes:
  """Class with functions that have default arguments and types."""
  def double(self, count: float = ...) -> float:
    """Returns the input multiplied by 2.

    Args:
      count: Input number that you want to double.

    Returns:
      A number that is the double of count.
    """
    ...
  
  def get_int(self, value: int = ...): # -> int:
    ...
  


