"""
This type stub file was generated by pyright.
"""

from fire import testutils

"""Tests for the test_components module."""
class TestComponentsTest(testutils.BaseTestCase):
  """Tests to verify that the test components are importable and okay."""
  def testTestComponents(self): # -> None:
    ...
  
  def testNonComparable(self): # -> None:
    ...
  


if __name__ == '__main__':
  ...
