"""
This type stub file was generated by pyright.
"""

from fire import testutils

"""Tests for the trace module."""
class FireTraceTest(testutils.BaseTestCase):
  def testFireTraceInitialization(self): # -> None:
    ...
  
  def testFireTraceGetResult(self): # -> None:
    ...
  
  def testFireTraceHasError(self): # -> None:
    ...
  
  def testAddAccessedProperty(self): # -> None:
    ...
  
  def testAddCalledCallable(self): # -> None:
    ...
  
  def testAddCalledRoutine(self): # -> None:
    ...
  
  def testAddInstantiatedClass(self): # -> None:
    ...
  
  def testAddCompletionScript(self): # -> None:
    ...
  
  def testAddInteractiveMode(self): # -> None:
    ...
  
  def testGetCommand(self): # -> None:
    ...
  
  def testGetCommandWithQuotes(self): # -> None:
    ...
  
  def testGetCommandWithFlagQuotes(self): # -> None:
    ...
  


class FireTraceElementTest(testutils.BaseTestCase):
  def testFireTraceElementHasError(self): # -> None:
    ...
  
  def testFireTraceElementAsStringNoMetadata(self): # -> None:
    ...
  
  def testFireTraceElementAsStringWithTarget(self): # -> None:
    ...
  
  def testFireTraceElementAsStringWithTargetAndLineNo(self): # -> None:
    ...
  


if __name__ == '__main__':
  ...
