"""
This type stub file was generated by pyright.
"""

"""OS specific console_attr helper functions."""
def GetTermSize(): # -> tuple[Any, Any] | tuple[Literal[80], Literal[24]]:
  """Gets the terminal x and y dimensions in characters.

  _GetTermSize*() helper functions taken from:
    http://stackoverflow.com/questions/263890/

  Returns:
    (columns, lines): A tuple containing the terminal x and y dimensions.
  """
  ...

_ANSI_CSI = ...
_CONTROL_D = ...
_CONTROL_Z = ...
_WINDOWS_CSI_1 = ...
_WINDOWS_CSI_2 = ...
def GetRawKeyFunction(): # -> Callable[[], Any | str | None] | Callable[[], None]:
  """Returns a function that reads one keypress from stdin with no echo.

  Returns:
    A function that reads one keypress from stdin with no echo or a function
    that always returns None if stdin does not support it.
  """
  ...

